config/routes.rb
Rails.application.routes.draw do
  get 'comment_response/index'
  get 'comments/index'
  get 'follows/index'
  get '/animes', to: 'animes#index'
  get '/animes/busca', to: 'animes#busca', as: 'busca_animes'
  get "/animes/render_anime_partial", to: "animes#render_anime_partial"
  post '/animes/cadastrar_anime_from_json', to: 'animes#cadastrar_anime_from_json', as: 'cadastrar_anime_from_json_animes'


  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'animes#index'

  resources :animes do
    get 'show_from_json', on: :collection
    resources :comments
    resources :comment_responses
  end

  # resources :follows
 
  resources :users
  resources :follows do 
    collection do
      get 'favorites', as: :favorites
      post '/add_follow/:anime_id', to: 'follows#add_follow', as: :add
      delete '/remove_follow/:id', to: 'follows#remove_follow', as: :remove
      post '/add_favorite/:anime_id', to: 'follows#add_favorite', as: :add_favorite
      delete '/remove_favorite/:id', to: 'follows#remove_favorite', as: :remove_favorite
    end
  end

  
end

app/models/anime.rb
class Anime < ApplicationRecord
  belongs_to :user
  has_many :follows, dependent: :destroy
  has_many :users, through: :follows

  require 'httparty'
  require 'json'

  # enum status: { ativo: 0, excluido: 1}
  validates :anime_id, presence: true, uniqueness: true
  
  # Validations
  # validates :name, presence: true,length: { minimum: 5, maximum: 100 }
  # validates :description, presence: true,length: { minimum: 5, maximum: 1000 }
  # validates :genres, presence: true,length: { minimum: 5, maximum: 100 }
  # validates :episodes, presence: true
  # validates :studios, presence: true,length: { minimum: 5, maximum: 100 }
  # validates :duration, presence: true
  # validates :situation, presence: true,length: { minimum: 5, maximum: 100 }


end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :set_anime, only: %i[ show edit update destroy ]

  def index
    # @animes = current_user.admin? ?  Anime.order(id: :desc) : current_user.animes.where(status: "ativo")
    @api_service = AnimeService.new
    @animes = Anime.all
    # @resultados = @api_service.obter_recurso
    @detalhes_animes = obter_detalhes_para_cada_anime(@animes)

    begin

      @anime_data = api_service
      puts @anime_data.class
      # Lógica para lidar com o recurso aqui


      render json: recurso
    rescue => e
      # Lidar com erros, talvez renderizar uma mensagem de erro
      flash[:error] = "Erro ao obter dados da API: #{e.message}"
      # render json: { erro: e.message }, status: :unprocessable_entity
    end

    render 'index'
  end

  def all
    @animes = current_user.admin? ?  Anime.order(name: :asc) : Anime.where(status: "ativo").order(name: :asc)
  end

  def show
      @animes = Anime.all
  end

  def busca
    api_service = AnimeService.new

    begin
      q = params[:q]
      @resultados = api_service.buscar_animes(q)
      redirect_to show_from_json_animes_path(anime: dados_json)
    rescue => e
      flash[:error] = "Erro ao realizar a busca: #{e.message}"
    end

    render 'busca'
  end

  def show_from_json
    @anime_data = JSON.parse(params[:anime], symbolize_names: true)
    @anime_comment = @anime_data[:mal_id]
    @animess = Anime.find_by(anime_id: @anime_comment)
    @comment = Comment.new
    if @animess != nil
      @comments = Comment.where(anime_id: @animess.id)
      @comment_responses = CommentResponse.joins(comment: :anime).where(comments: { anime_id: @animess.id })
    end
  end

  def cadastrar_anime_from_json
    @anime_data = JSON.parse(params[:anime], symbolize_names: true)
    @anime = Anime.new(

      anime_id: @anime_data[:mal_id],
      user_id: current_user.id
    )
    @anime.save
    render 'show_from_json'
  end

  def result
    @animes = Anime.all
  end

  def new
      @anime = Anime.new
  end

  def create
      @anime = Anime.new(anime_params)
      if @anime.save
        redirect_to animes_path
    else
        render :edit
    end
  end

  def edit 
  end

  def update 
      if @anime.update(anime_params)
          redirect_to animes_path
      else
          render :edit
      end
  end

  def destroy 
    #   @anime.destroy
        @anime.update(status: "excluido")
      redirect_to animes_path
  end

  def search
    result = Anime.anime_search(params[:q])
    # puts result.class
    @animes = result.map do |anime|
      Anime.new_from_search(anime)
    end
    pp @animes
    # render json: @animes

  end


  private

  def set_anime
      @anime = Anime.find(params[:id])
      # authorize @user
  end

  def obter_detalhes_para_cada_anime(animes)
    detalhes_animes = []
    @animes2 = animes
    @animes2.each do |anime|
      detalhes_animes << @api_service.obter_detalhes_do_anime(anime.anime_id)
    end
    detalhes_animes
  end

  def anime_params
      params.require(:anime).permit(:user_id,:name, :description, :image_url, :preview , :genres, :episodes, :status, :studios, :duration, :situation)
  end
end

app/helpers/anime_helper.rb
module AnimeHelper
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/views/animes/_anime.html.erb
<div class="row d-flex justify-content-center">
    <div class="header-box-container col-sm-3">
        <div class="header-icons ">
            <p class="text-icons icon-arrow">
                <%= link_to(animes_path) do %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"></path>
                    </svg>
                <% end %>
            </p>
        </div>
    </div>

    <div class="page-content">
        <div class="detail">
            <h1 class="detail--title"> <%= anime[:title] %></h1>
            <div class="icon-content">
                
            </div>
            <div class="detail--main-content" >
                <img src="<%= anime[:images][:jpg][:image_url] %>" alt="image" class="media-poster">
                <div class="detail--main-content--synopsis">
                    <div class="detail--main-content--genres">
                        <strong>Synopsis:</strong>
                        <span class="detail--main-content--synopsis--content"><%= anime[:synopsis]  %></span>
                    </div>
                    <div class="detail--main-content--genres">
                        <strong>Genres: </strong>
                        <% anime[:genres].each_with_index do |genre,index| %>
                        	<span class="detail--main-content--genre"><%= genre[:name] %></span>
													<%= ',' unless index == anime[:genres].length - 1 %>
                        <% end %>
                        <strong>Studios: </strong>
												<% anime[:studios].each_with_index do |studio,index| %>
                        	<span class="detail--main-content--genre"><%= studio[:name] %></span>
													<%= ',' unless index == anime[:genres].length - 1 %>
                        <% end %>
                        <strong>Numero de episódios: </strong>
                        <span class="detail--main-content--genre"> <%= anime[:episodes] %></span>
                        <strong>Situação: </strong>
                        <span class="detail--main-content--genre"> <%= anime[:status] %></span>
                    </div>
                    <%= form_with(model: @anime, url: cadastrar_anime_from_json_animes_path(anime: @anime_data.to_json), method: :post) do |form| %>
                        <%= form.hidden_field :anime_id, value: @anime_data[:mal_id] %>
                        <%= form.submit 'Cadastrar este Anime',class: "primary" %>
                    <% end %>
                    < 
                    <!-- Mais detalhes do anime -->
                    <!-- Formulário para cadastrar um comentário -->
                    <% if @animess.present? %>
                        <%= form_with(model: Comment.new, url: anime_comments_path(@animess.id), method: :post) do |form| %>
                        <%= form.hidden_field :user_id, value: current_user.id %>
                        <%= form.hidden_field :anime_id, value: @animess.id %>
                        <div class="field">
                            <%= form.label :content, "Comentário" %>
                            <%= form.text_area :content, rows: 4 %>
                        </div>
                        <div class="actions">
                            <%= form.submit "Enviar Comentário" %>
                        </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/animes/_card.html.erb
<div class="tab-pane fade show active" id="course-pills-tabs-1" role="tabpanel" aria-labelledby="course-pills-tab-1">
    <div class="row g-4">
        <% animes.each do |anime| %>
            <!-- Card item START -->
            <div class="col-sm-6 col-lg-4 col-xl-3">
                <div class="card shadow h-100">
                    <%= link_to(show_from_json_animes_path(anime: anime.to_json), class: "show-anime-link") do %>
                        <!-- Image -->
                        <img src="<%=anime["images"]["jpg"]["image_url"]%>" class="card-img-top" alt="course image">
                        <!-- Card body -->
                        <div class="card-body pb-0">
                            <!-- Title -->
                            <h5 class="card-title fw-normal"><a href="#"><%= anime["title"]%></a></h5>
                        </div>
                    <%end %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/animes/_comment_responses.html.erb
<div class="row d-flex justify-content-center">
  <div class="page-content">
    <div class="detail">     
      <div class="detail--main-content" >
        <div class="detail--main-content--synopsis">
          <% if comment_responses.present? %>
            <% comment_responses.each do |response| %>
              <div class="detail--main-content--genres">
                <strong>Resposta:</strong>
                <span class="detail--main-content--synopsis--content" style="color: red;"><%= response.user_id %></span>
                <span class="detail--main-content--synopsis--content" style="color: red;"><%= response.content %></span>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>               
    </div>
  </div>
</div>

app/views/animes/_comments.html.erb
<div class="row d-flex justify-content-center">
  <div class="page-content">
    <div class="detail">
      <% comments.each do |comment| %>
        <div class="detail--main-content" >
          <div class="detail--main-content--synopsis">
            <div class="detail--main-content--genres">
              <strong>user:</strong>
              <span class="detail--main-content--synopsis--content"><%= comment.user.name %></span>
            </div>
            <div class="detail--main-content--genres">
              <strong>Comentário:</strong>
              <span class="detail--main-content--synopsis--content"><%= comment.content %></span>
            </div>
            <%= form_with(model: CommentResponse.new, url: anime_comment_responses_path(comment.id), method: :post) do |form| %>
              <%= form.hidden_field :user_id, value: current_user.id %>
              <%= form.hidden_field :comment_id, value: comment.id %>
              <div class="field">
                  <%= form.label :content, "Resposta" %>
                  <%= form.text_area :content, rows: 3 %>
              </div>
              <div class="actions">
                  <%= form.submit "Enviar Resposta" %>
              </div>
            <% end %>
            <% if @comment_responses.present? %>
            <%= render partial: 'comment_responses', locals: { comment_responses: comment.comment_responses } %>
            <% end %>
          </div>
        </div>          
      <% end %>
    </div>
  </div>
</div>

app/views/animes/_form.html.erb
  
<div class="card" style="background-color:#f6f6f6;">
  <div class="card-body">
    <%= form_with model: anime do |form| %>
      
      <div class="col-6">
          <div class="form-group">
            <%= form.label :user_id %>
            <%= form.text_field :user_id, class: "form-control" %>
            <% anime.errors.full_messages_for(:user_id).each do |message| %>
                <div><%= message %></div>
            <% end %>
          </div>
      </div>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
        <% anime.errors.full_messages_for(:name).each do |message| %>
                <div><%= message %></div>
            <% end %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_field :description, class: "form-control" %>
        <% anime.errors.full_messages_for(:description).each do |message| %>
                <div><%= message %></div>
            <% end %>
      </div>
      <div class="form-group">
        <%= form.label :image_url %>
        <%= form.text_field :image_url, class: "form-control" %>
        <% anime.errors.full_messages_for(:description).each do |message| %>
                <div><%= message %></div>
            <% end %>
      </div>
      <div class="form-row">
        <div class="col-6">
          <div class="form-group">
            <%= form.label :genres %>
            <%= form.text_field :genres, class: "form-control" %>
            <% anime.errors.full_messages_for(:genres).each do |message| %>
                <div><%= message %></div>
            <% end %>
          </div>
        </div>
        <div class="col-6">
          <div class="form-group">
            <%= form.label :episodes %>
            <%= form.number_field :episodes, class: "form-control" %>
            <% anime.errors.full_messages_for(:episodes).each do |message| %>
                <div><%= message %></div>
            <% end %>
          </div>
        </div>
    
        <div class="col-6">
          <div class="form-group">
            <%= form.label :studios %>
            <%= form.text_field :studios, class: "form-control" %>
            <% anime.errors.full_messages_for(:studios).each do |message| %>
                <div><%= message %></div>
            <% end %>
          </div>
        </div>
        <div class="col-6">
          <div class="form-group">
            <%= form.label :duration %>
            <%= form.number_field :duration, class: "form-control" %>
            <% anime.errors.full_messages_for(:duration).each do |message| %>
                <div><%= message %></div>
            <% end %>
          </div>
        </div>
        <div class="col-6">
          <div class="form-group">
            <%= form.label :situation %>
            <%= form.text_field :situation, class: "form-control" %>
            <% anime.errors.full_messages_for(:situation).each do |message| %>
                <div><%= message %></div>
            <% end %>
          </div>
        </div>

      </div>
      <%= form.submit %>
    <% end %>
  </div>
</div>

app/views/animes/all.html.erb
<section class="position-relative overflow-hidden pt-5 pt-lg-3">
	<!-- Content START -->
	<div class="container background">
		<!-- Title -->
		<div class="row align-items-center g-5">
			<div class="col-lg-5 col-xl-6 position-relative z-index-1 text-center text-lg-start mb-5 mb-sm-0">
				<h1 class="mb-0 display-6">MyAnimes. Crie sua lista de animes favoritos!</h1>
			</div>
		</div>
	</div>
</section>
<!-- Content END -->

<section>
	<div class="container">
		<div class="row mb-4 title">
			<div class="col-lg-8 mx-auto text-center"><h2 class="fs-1 title">Animes Cadastrados</h2></div>
			<div class="ms-auto p-2 bd-highlight">
				<%= link_to(new_anime_path,class: "title-style") do %>
					<button type="button" class="btn btn-success button-anime">Cadastrar Anime</button>
				<% end %>
			</div>
		</div>

		<!-- Cards content START -->
		<div class="tab-content" id="course-pills-tabContent">
			<%= render 'card', animes: @animes %>
		</div>
	</div>
</section>

app/views/animes/busca.html.erb
<!-- app/views/animes/busca.html.erb -->
<h1>Resultados da Busca</h1>

<% if @resultados.present? %>
  <% @resultados.each do |anime| %>
    <div class="anime-result">
      <h2><%= anime["title"] %></h2>
      <p><strong>Descrição:</strong> <%= anime["synopsis"] %></p>
      <% if anime["images"] && anime["images"]["jpg"] && anime["images"]["jpg"]["image_url"].present? %>
        <%= image_tag anime["images"]["jpg"]["image_url"], alt: "Imagem do Anime", size: "100x100" %>
        <% anime[:mal_id] %>
        <%= link_to "Ver Detalhes", show_from_json_animes_path(anime: anime.to_json), class: "show-anime-link" %>
      <% else %>
        <p><em>Nenhuma imagem disponível</em></p>
      <% end %>
    </div>
  <% end %>
<% else %>
  <p>Nenhum resultado encontrado.</p>
<% end %>

app/views/animes/edit.html.erb
<h1>Editing Anime</h1>

<%= render 'form', anime: @anime %>

<%= link_to 'Show', @anime %> |
<%= link_to 'Back', animes_path %>

app/views/animes/index.html.erb
<%= form_tag busca_animes_path, method: :get,  remote: true do %>
  <%= text_field_tag :q, params[:q], placeholder: "Digite para buscar..." %>
  <%= submit_tag "Buscar" %>
<% end %>
<section class="position-relative overflow-hidden pt-5 pt-lg-3">
	<!-- Content START -->
	<div class="container background">
		<!-- Title -->
		<div class="row align-items-center g-5">
			<div class="col-lg-5 col-xl-6 position-relative z-index-1 text-center text-lg-start mb-5 mb-sm-0">
				<h1 class="mb-0 display-6">MyAnimes. Crie sua lista de animes favoritos!</h1>
			</div>
		</div>
	</div>
</section>
<!-- Content END -->

<section>
	<div class="container">
		<div class="row mb-4 title">
			<div class="col-lg-8 mx-auto text-center">
				<h2 class="fs-1 title">Seus Animes</h2>
			</div>
		</div>

		<!-- Cards content START -->
		<div class="tab-content" id="course-pills-tabContent">
		  <%= render 'card', animes: @detalhes_animes %>
			
		</div>
	</div>
</section>

app/views/animes/new.html.erb
<h2> Add Anime</h2>
 <%= render 'form', anime: @anime %>

app/views/animes/search.js.erb
<% @animes.each do |anime| %>
$(".search-box").append('<%= link_to(anime) do %><div class="search-image"><img class="image img-fluid" src="<%= anime.image_url%>" style="height: 79px;"><%= anime.name %></div><% end %>');
console.log('<%= anime.name %>');
<% end %>

app/views/animes/show.html.erb
<div class="container style-list">
    <div class="header-container">
       <%= render 'anime', anime: @anime %>
    </div>
</div>

app/views/animes/show_from_json.html.erb
<div class="container style-list">
    <div class="header-container">
       <% if @anime_data.present? %>
        <%= render 'anime', anime: @anime_data %>
         <% if @comments.present? %>
          <%= render 'comments', comments: @comments%>
        <% end %>
      <% else %>
        <p>Nenhum anime encontrado.</p>
      <% end %>
    </div>
</div>