config/routes.rb
Rails.application.routes.draw do
  get 'comment_response/index'
  get 'comments/index'
  get 'follows/index'
  get '/animes', to: 'animes#index'
  get '/animes/busca', to: 'animes#busca', as: 'busca_animes'
  get "/animes/render_anime_partial", to: "animes#render_anime_partial"
  post '/animes/cadastrar_anime_from_json', to: 'animes#cadastrar_anime_from_json', as: 'cadastrar_anime_from_json_animes'


  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'animes#index'

  resources :animes do
    get 'show_from_json', on: :collection
    resources :comments
    resources :comment_responses
  end

  # resources :follows
 
  resources :users
  resources :follows do 
    collection do
      get 'favorites', as: :favorites
      post '/add_follow/:anime_id', to: 'follows#add_follow', as: :add
      delete '/remove_follow/:id', to: 'follows#remove_follow', as: :remove
      post '/add_favorite/:anime_id', to: 'follows#add_favorite', as: :add_favorite
      delete '/remove_favorite/:id', to: 'follows#remove_favorite', as: :remove_favorite
    end
  end

  
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :anime
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def index
    @follows = current_user.follows.order(id: :desc) 
  end

  def favorites
    @favorites = current_user.admin? ? Follow.where(favorite: true) : current_user.follows.where(favorite: true)
  end
  def show 
    @follows = Follow.all
  end

  def new
    @follow = current_user.follow.new
  end

  def add_follow
    if current_user.follows.find_by(anime_id: params[:anime_id])
    else
      @follow = current_user.follows.new(anime_id: params[:anime_id])
      @follow.save
      redirect_to  root_path, notice: 'follow adicionado com sucesso!'
    end
  end

  def edit 
  end

  def remove_follow
    @follow = current_user.follows.find_by(id: params[:id])
    @follow.destroy
    # redirect_to follows_path, notice: 'follow removido com sucesso!'
    @follow.inspect
  end

  def add_favorite
    if current_user.follows.where(favorite: true).find_by(anime_id: params[:anime_id])
      puts "Favorito ja existe"
    end
    if current_user.follows.find_by(anime_id: params[:anime_id])
      puts "Follow ja existe"
      @follow = current_user.follows.find_by(anime_id: params[:anime_id])
      @follow.update(favorite: true)
    else
      @follow = current_user.follows.new(anime_id: params[:anime_id], favorite: true)
      @follow.save
    end
    
  end
 
  def remove_favorite
    @follow = current_user.follows.find_by(id: params[:id])
    @follow.update(favorite: false)
    redirect_to favorites_follows_path, notice: 'favoritos removido com sucesso!'
  end


  
  private

    def set_user
        @user = User.find(params[:id])
        # authorize @user
    end

    def follow_params
        params.required(:follow).permit(:user_id , :anime_id, :favorite)
    end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/favorites.html.erb
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">description</th>
      <th scope="col">genres</th>
      <th scope="col">episodes</th>
      <th scope="col">status</th>
      <th scope="col">#</th>
      <th scope="col">#</th>
      
    </tr>
  </thead>
  <tbody>
    <% @favorites.each do |follow| %>
      
        <tr>
          <td><%= follow.anime.id%></td>
          <td><%= follow.anime.name%></td>
          <td><%= follow.anime.description%></td>
          <td><%= follow.anime.genres%></td>
          <td><%= follow.anime.episodes%></td>
          <td><%= follow.anime.status%></td>
          <td><%= link_to("Show",follow.anime) %></td>
          <td><%= link_to("Deletar",remove_favorite_follows_path(follow),method: :delete,data: {confirm: "Are you sure?"})%></td>

        </tr>
      
    <% end %>
  </tbody>
</table>