config/routes.rb
Rails.application.routes.draw do
  get 'comment_response/index'
  get 'comments/index'
  get 'follows/index'
  get '/animes', to: 'animes#index'
  get '/animes/busca', to: 'animes#busca', as: 'busca_animes'
  get "/animes/render_anime_partial", to: "animes#render_anime_partial"
  post '/animes/cadastrar_anime_from_json', to: 'animes#cadastrar_anime_from_json', as: 'cadastrar_anime_from_json_animes'


  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'animes#index'

  resources :animes do
    get 'show_from_json', on: :collection
    resources :comments
    resources :comment_responses
  end

  # resources :follows
 
  resources :users
  resources :follows do 
    collection do
      get 'favorites', as: :favorites
      post '/add_follow/:anime_id', to: 'follows#add_follow', as: :add
      delete '/remove_follow/:id', to: 'follows#remove_follow', as: :remove
      post '/add_favorite/:anime_id', to: 'follows#add_favorite', as: :add_favorite
      delete '/remove_favorite/:id', to: 'follows#remove_favorite', as: :remove_favorite
    end
  end

  
end

app/views/layouts/_topnavbar.html.erb
<% if user_signed_in? %>
	<header class="navbar-light navbar-sticky header-static">
		<!-- Logo Nav START -->
		<nav class="navbar navbar-expand-xl">
			<div class="container-fluid px-3 px-xl-5">
				<!-- Logo START -->
				<%= link_to(root_path,class: "navbar-brand") do %>
					<h3>My-Animes</h3>
				<% end %>
				<!-- Logo END -->

				<!-- Responsive navbar toggler -->
				<button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-animation">
						<span></span>
						<span></span>
						<span></span>
					</span>
				</button>

				<!-- Main navbar START -->
				<div class="navbar-collapse w-100 collapse" id="navbarCollapse">

					

					<!-- Nav Main menu START -->
					<ul class="navbar-nav navbar-nav-scroll me-auto">
						<!-- Nav item 1 Demos -->
						<li class="nav-item dropdown">
							<%# <a class="nav-link dropdown-toggle active" href="#" id="demoMenu" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Demos</a> %>
							<%= link_to "Inicio", root_path,class: "nav-link "%>
						</li>

						<!-- Nav item 2 Pages -->
						<li class="nav-item dropdown">
							<%# <%= link_to "Animes", all_animes_path,class: "nav-link "%> 
						</li>

						<!-- Nav item 3 Account -->
						<li class="nav-item dropdown">
							<%= link_to "Favoritos", favorites_follows_path,class: "nav-link "%>
						</li>

						

						<!-- Nav item 4 Megamenu-->
						<li class="nav-item dropdown dropdown-fullwidth">
							<%= link_to "Seguidos", follows_path,class: "nav-link "%>
						</li>

						<li class="nav-item dropdown">
							<%= link_to "Usuarios", users_path,class: "nav-link "%>
						</li>

						
					</ul>
					<!-- Nav Main menu END -->

					<!-- Nav Search START -->
					<div class="nav my-3 my-xl-0 px-4 flex-nowrap align-items-center">
						<div class="nav-item w-100">
							<form class="position-relative">
								<input class="form-control pe-5 bg-transparent" type="search" placeholder="Search" aria-label="Search" id="inputSearch" type="text" onkeyup="goBackInitialTracks(event)">
								<button class="btn bg-transparent px-2 py-0 position-absolute top-50 end-0 translate-middle-y" type="submit" ><i class="fas fa-search fs-6 "></i></button>

								<div class="search-box" id="track_list">
									
								</div>
							</form>
						</div>
						
					</div>
					<!-- Nav Search END -->
				</div>
				<!-- Main navbar END -->

				<!-- Profile START -->
				<div class="dropdown ms-1 ms-lg-0">
					
					<a class="avatar avatar-sm p-0 dropbtn"  id="profileDropdown" role="button" onclick="myFunction()">
						<img class="avatar-img rounded-circle drop" src="https://eduport.webestica.com/assets/images/avatar/01.jpg" alt="avatar">
					</a>
					<ul class="dropdown-menu dropdown-animation dropdown-menu-end shadow pt-3 dropdown-content options" id="options" aria-labelledby="profileDropdown">
						<!-- Profile info -->
						<!-- Links -->
						<li><%= link_to 'Edit User', edit_user_registration_path, class: 'dropdown-item' %></li>
						
						<li><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item bg-danger-soft-hover' %>
					</ul></li>
						
				</div>
				<!-- Profile START -->
			</div>
		</nav>
		<!-- Logo Nav END -->
	</header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAnimes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag "application"  , media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "header" %>
    <%= javascript_include_tag "search" %>


  </head>

  <body>
    <%= render 'layouts/topnavbar' %>
    
      <%= yield %>
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>

</html>